/**
 * Q-Learn Nexus - Quantum Framework Code Converters & Intermediate Representation (IR)
 * Exports Circuit IR to Qiskit (Python), PennyLane, Cirq, and OpenQASM 2.0
 * @license Apache-2.0
 */

import { QuantumCircuitIR, CircuitGate } from '../types/quantum';

export function irToQiskit(ir: QuantumCircuitIR): string {
  const numQ = ir.qubits || 2;
  const numC = ir.classicalBits || numQ;
  const sortedGates = [...(ir.gates || [])].sort((a, b) => a.stepIndex - b.stepIndex);

  let code = `# ========================================================\n`;
  code += `# Generated by Q-Learn Nexus (AI Quantum Platform)\n`;
  code += `# Circuit: ${ir.name || 'Untitled Circuit'} (${numQ} Qubits)\n`;
  code += `# ========================================================\n\n`;
  code += `import numpy as np\n`;
  code += `from qiskit import QuantumCircuit, transpile\n`;
  code += `from qiskit_aer import AerSimulator\n`;
  code += `from qiskit.visualization import plot_histogram, plot_bloch_multivector\n\n`;
  code += `# Initialize Quantum Circuit\n`;
  code += `qc = QuantumCircuit(${numQ}, ${numC}, name="${ir.name || 'q_circuit'}")\n\n`;

  for (const g of sortedGates) {
    const t = g.targets[0];
    const c = g.controls?.[0];

    switch (g.type) {
      case 'H':
        code += `qc.h(${t})\n`;
        break;
      case 'X':
        code += `qc.x(${t})\n`;
        break;
      case 'Y':
        code += `qc.y(${t})\n`;
        break;
      case 'Z':
        code += `qc.z(${t})\n`;
        break;
      case 'S':
        code += `qc.s(${t})\n`;
        break;
      case 'Sdg':
        code += `qc.sdg(${t})\n`;
        break;
      case 'T':
        code += `qc.t(${t})\n`;
        break;
      case 'Tdg':
        code += `qc.tdg(${t})\n`;
        break;
      case 'Rx':
        code += `qc.rx(${g.params?.theta ?? 0}, ${t})\n`;
        break;
      case 'Ry':
        code += `qc.ry(${g.params?.theta ?? 0}, ${t})\n`;
        break;
      case 'Rz':
        code += `qc.rz(${g.params?.theta ?? 0}, ${t})\n`;
        break;
      case 'CX':
        if (c !== undefined) code += `qc.cx(${c}, ${t})\n`;
        break;
      case 'CZ':
        if (c !== undefined) code += `qc.cz(${c}, ${t})\n`;
        break;
      case 'CCX':
        if (g.controls && g.controls.length >= 2) {
          code += `qc.ccx(${g.controls[0]}, ${g.controls[1]}, ${t})\n`;
        }
        break;
      case 'SWAP':
        if (g.targets.length >= 2) {
          code += `qc.swap(${g.targets[0]}, ${g.targets[1]})\n`;
        }
        break;
      case 'M':
        code += `qc.measure(${t}, ${t})\n`;
        break;
      case 'Barrier':
        code += `qc.barrier()\n`;
        break;
    }
  }

  code += `\n# Measure all qubits if not explicitly measured\n`;
  const hasMeasure = sortedGates.some((g) => g.type === 'M');
  if (!hasMeasure) {
    code += `qc.measure_all()\n\n`;
  }

  code += `# Run high-performance simulation on AerSimulator\n`;
  code += `simulator = AerSimulator()\n`;
  code += `compiled_circuit = transpile(qc, simulator)\n`;
  code += `job = simulator.run(compiled_circuit, shots=1024)\n`;
  code += `result = job.result()\n`;
  code += `counts = result.get_counts()\n\n`;
  code += `print("--- Q-Learn Nexus Simulation Results ---")\n`;
  code += `print("Measurement Counts:", counts)\n`;
  code += `print("Circuit Depth:", qc.depth())\n`;

  return code;
}

export function irToPennyLane(ir: QuantumCircuitIR): string {
  const numQ = ir.qubits || 2;
  const sortedGates = [...(ir.gates || [])].sort((a, b) => a.stepIndex - b.stepIndex);

  let code = `# ========================================================\n`;
  code += `# PennyLane Variational Quantum Circuit\n`;
  code += `# Circuit: ${ir.name || 'PennyLane Circuit'} (${numQ} Wires)\n`;
  code += `# ========================================================\n\n`;
  code += `import pennylane as qml\n`;
  code += `import numpy as np\n\n`;
  code += `dev = qml.device("default.qubit", wires=${numQ}, shots=1024)\n\n`;
  code += `@qml.qnode(dev)\n`;
  code += `def quantum_circuit():\n`;

  if (sortedGates.length === 0) {
    code += `    # Empty circuit (Identity)\n`;
    code += `    return qml.probs(wires=range(${numQ}))\n`;
    return code;
  }

  for (const g of sortedGates) {
    const t = g.targets?.[0] ?? 0;
    const c = g.controls?.[0];

    switch (g.type) {
      case 'H':
        code += `    qml.Hadamard(wires=${t})\n`;
        break;
      case 'X':
        code += `    qml.PauliX(wires=${t})\n`;
        break;
      case 'Y':
        code += `    qml.PauliY(wires=${t})\n`;
        break;
      case 'Z':
        code += `    qml.PauliZ(wires=${t})\n`;
        break;
      case 'S':
        code += `    qml.S(wires=${t})\n`;
        break;
      case 'T':
        code += `    qml.T(wires=${t})\n`;
        break;
      case 'Rx':
        code += `    qml.RX(${g.params?.theta ?? 0}, wires=${t})\n`;
        break;
      case 'Ry':
        code += `    qml.RY(${g.params?.theta ?? 0}, wires=${t})\n`;
        break;
      case 'Rz':
        code += `    qml.RZ(${g.params?.theta ?? 0}, wires=${t})\n`;
        break;
      case 'CX':
        if (c !== undefined) code += `    qml.CNOT(wires=[${c}, ${t}])\n`;
        break;
      case 'CZ':
        if (c !== undefined) code += `    qml.CZ(wires=[${c}, ${t}])\n`;
        break;
      case 'SWAP':
        if (g.targets && g.targets.length >= 2) code += `    qml.SWAP(wires=[${g.targets[0]}, ${g.targets[1]}])\n`;
        break;
      case 'CCX':
        if (g.controls && g.controls.length >= 2) {
          code += `    qml.Toffoli(wires=[${g.controls[0]}, ${g.controls[1]}, ${t}])\n`;
        }
        break;
    }
  }

  code += `    return qml.probs(wires=range(${numQ}))\n\n`;
  code += `# Execute and print probabilities\n`;
  code += `probs = quantum_circuit()\n`;
  code += `print("PennyLane State Probabilities:", probs)\n`;

  return code;
}

export function irToCirq(ir: QuantumCircuitIR): string {
  const numQ = ir.qubits || 2;
  const sortedGates = [...(ir.gates || [])].sort((a, b) => a.stepIndex - b.stepIndex);

  let code = `# ========================================================\n`;
  code += `# Google Cirq Quantum Circuit\n`;
  code += `# Circuit: ${ir.name || 'Cirq Circuit'} (${numQ} Qubits)\n`;
  code += `# ========================================================\n\n`;
  code += `import cirq\n`;
  code += `import numpy as np\n\n`;
  code += `# Create line qubits\n`;
  code += `qubits = [cirq.LineQubit(i) for i in range(${numQ})]\n`;
  code += `circuit = cirq.Circuit()\n\n`;

  for (const g of sortedGates) {
    const targetIdx = g.targets?.[0] ?? 0;
    const t = `qubits[${targetIdx}]`;
    const c = g.controls && g.controls.length > 0 ? `qubits[${g.controls[0]}]` : '';

    switch (g.type) {
      case 'H':
        code += `circuit.append(cirq.H(${t}))\n`;
        break;
      case 'X':
        code += `circuit.append(cirq.X(${t}))\n`;
        break;
      case 'Y':
        code += `circuit.append(cirq.Y(${t}))\n`;
        break;
      case 'Z':
        code += `circuit.append(cirq.Z(${t}))\n`;
        break;
      case 'S':
        code += `circuit.append(cirq.S(${t}))\n`;
        break;
      case 'T':
        code += `circuit.append(cirq.T(${t}))\n`;
        break;
      case 'Rx':
        code += `circuit.append(cirq.rx(${g.params?.theta ?? 0})(${t}))\n`;
        break;
      case 'Ry':
        code += `circuit.append(cirq.ry(${g.params?.theta ?? 0})(${t}))\n`;
        break;
      case 'Rz':
        code += `circuit.append(cirq.rz(${g.params?.theta ?? 0})(${t}))\n`;
        break;
      case 'CX':
        if (c) code += `circuit.append(cirq.CNOT(${c}, ${t}))\n`;
        break;
      case 'CZ':
        if (c) code += `circuit.append(cirq.CZ(${c}, ${t}))\n`;
        break;
      case 'SWAP':
        if (g.targets && g.targets.length >= 2) code += `circuit.append(cirq.SWAP(qubits[${g.targets[0]}], qubits[${g.targets[1]}]))\n`;
        break;
      case 'CCX':
        if (g.controls && g.controls.length >= 2) {
          code += `circuit.append(cirq.TOFFOLI(qubits[${g.controls[0]}], qubits[${g.controls[1]}], ${t}))\n`;
        }
        break;
      case 'M':
        code += `circuit.append(cirq.measure(${t}, key='m_${targetIdx}'))\n`;
        break;
    }
  }

  code += `\n# Simulate using Cirq Simulator\n`;
  code += `simulator = cirq.Simulator()\n`;
  code += `result = simulator.simulate(circuit)\n`;
  code += `print("Cirq Circuit Diagram:")\n`;
  code += `print(circuit)\n`;
  code += `print("\\nFinal Statevector:\\n", result.state_vector())\n`;

  return code;
}

export function irToOpenQASM(ir: QuantumCircuitIR): string {
  const numQ = ir.qubits || 2;
  const numC = ir.classicalBits || numQ;
  const sortedGates = [...(ir.gates || [])].sort((a, b) => a.stepIndex - b.stepIndex);

  let qasm = `OPENQASM 2.0;\n`;
  qasm += `include "qelib1.inc";\n\n`;
  qasm += `qreg q[${numQ}];\n`;
  qasm += `creg c[${numC}];\n\n`;

  for (const g of sortedGates) {
    const t = g.targets?.[0] ?? 0;
    const c = g.controls?.[0];

    switch (g.type) {
      case 'H':
        qasm += `h q[${t}];\n`;
        break;
      case 'X':
        qasm += `x q[${t}];\n`;
        break;
      case 'Y':
        qasm += `y q[${t}];\n`;
        break;
      case 'Z':
        qasm += `z q[${t}];\n`;
        break;
      case 'S':
        qasm += `s q[${t}];\n`;
        break;
      case 'Sdg':
        qasm += `sdg q[${t}];\n`;
        break;
      case 'T':
        qasm += `t q[${t}];\n`;
        break;
      case 'Tdg':
        qasm += `tdg q[${t}];\n`;
        break;
      case 'Rx':
        qasm += `rx(${g.params?.theta ?? 0}) q[${t}];\n`;
        break;
      case 'Ry':
        qasm += `ry(${g.params?.theta ?? 0}) q[${t}];\n`;
        break;
      case 'Rz':
        qasm += `rz(${g.params?.theta ?? 0}) q[${t}];\n`;
        break;
      case 'CX':
        if (c !== undefined) qasm += `cx q[${c}], q[${t}];\n`;
        break;
      case 'CZ':
        if (c !== undefined) qasm += `cz q[${c}], q[${t}];\n`;
        break;
      case 'CCX':
        if (g.controls && g.controls.length >= 2) {
          qasm += `ccx q[${g.controls[0]}], q[${g.controls[1]}], q[${t}];\n`;
        }
        break;
      case 'SWAP':
        if (g.targets && g.targets.length >= 2) qasm += `swap q[${g.targets[0]}], q[${g.targets[1]}];\n`;
        break;
      case 'M':
        qasm += `measure q[${t}] -> c[${t}];\n`;
        break;
      case 'Barrier':
        qasm += `barrier q;\n`;
        break;
    }
  }

  return qasm;
}

/**
 * Basic QASM parser into QuantumCircuitIR
 */
export function qasmToIR(qasm: string): QuantumCircuitIR {
  const lines = qasm.split('\n').map((l) => l.trim()).filter((l) => l && !l.startsWith('//') && !l.startsWith('OPENQASM') && !l.startsWith('include'));
  let qubits = 2;
  let classicalBits = 2;
  const gates: CircuitGate[] = [];
  let step = 0;

  for (const line of lines) {
    if (line.startsWith('qreg')) {
      const match = line.match(/qreg\s+q\[(\d+)\]/);
      if (match) qubits = parseInt(match[1], 10);
    } else if (line.startsWith('creg')) {
      const match = line.match(/creg\s+c\[(\d+)\]/);
      if (match) classicalBits = parseInt(match[1], 10);
    } else if (line.startsWith('h ')) {
      const match = line.match(/q\[(\d+)\]/);
      if (match) {
        gates.push({ id: `gate_${Date.now()}_${step}`, type: 'H', targets: [parseInt(match[1], 10)], stepIndex: step++ });
      }
    } else if (line.startsWith('x ')) {
      const match = line.match(/q\[(\d+)\]/);
      if (match) {
        gates.push({ id: `gate_${Date.now()}_${step}`, type: 'X', targets: [parseInt(match[1], 10)], stepIndex: step++ });
      }
    } else if (line.startsWith('z ')) {
      const match = line.match(/q\[(\d+)\]/);
      if (match) {
        gates.push({ id: `gate_${Date.now()}_${step}`, type: 'Z', targets: [parseInt(match[1], 10)], stepIndex: step++ });
      }
    } else if (line.startsWith('cx ')) {
      const matches = [...line.matchAll(/q\[(\d+)\]/g)];
      if (matches.length >= 2) {
        gates.push({
          id: `gate_${Date.now()}_${step}`,
          type: 'CX',
          controls: [parseInt(matches[0][1], 10)],
          targets: [parseInt(matches[1][1], 10)],
          stepIndex: step++,
        });
      }
    }
  }

  return {
    version: '1.0',
    name: 'Imported QASM Circuit',
    qubits,
    classicalBits,
    gates,
  };
}
