/**
 * Q-Learn Nexus - Quantum SDK Adapters
 * Native transpilation & format adapters for Qiskit, PennyLane, Cirq, and OpenQASM.
 * @license Apache-2.0
 */

import { QuantumCircuitIR } from './engine';

export class QuantumAdapters {
  /**
   * Generates production Qiskit 1.x Python code.
   */
  public static toQiskit(ir: QuantumCircuitIR): string {
    const lines: string[] = [
      '# Generated by Q-Learn Nexus Quantum Transpiler (Qiskit 1.x)',
      'from qiskit import QuantumCircuit',
      'from qiskit_aer import AerSimulator',
      'import numpy as np',
      '',
      `qc = QuantumCircuit(${ir.qubits}, ${ir.classicalBits})`,
      `qc.name = "${ir.name.replace(/"/g, '\\"')}"`,
      '',
    ];

    const sorted = [...ir.gates].sort((a, b) => a.stepIndex - b.stepIndex);

    for (const g of sorted) {
      switch (g.type) {
        case 'H':
          lines.push(`qc.h(${g.targets[0]})`);
          break;
        case 'X':
          lines.push(`qc.x(${g.targets[0]})`);
          break;
        case 'Y':
          lines.push(`qc.y(${g.targets[0]})`);
          break;
        case 'Z':
          lines.push(`qc.z(${g.targets[0]})`);
          break;
        case 'S':
          lines.push(`qc.s(${g.targets[0]})`);
          break;
        case 'Sdg':
          lines.push(`qc.sdg(${g.targets[0]})`);
          break;
        case 'T':
          lines.push(`qc.t(${g.targets[0]})`);
          break;
        case 'Tdg':
          lines.push(`qc.tdg(${g.targets[0]})`);
          break;
        case 'CX':
        case 'CNOT':
          lines.push(`qc.cx(${g.controls?.[0] ?? 0}, ${g.targets[0]})`);
          break;
        case 'CZ':
          lines.push(`qc.cz(${g.controls?.[0] ?? 0}, ${g.targets[0]})`);
          break;
        case 'SWAP':
          lines.push(`qc.swap(${g.targets[0]}, ${g.targets[1] ?? 1})`);
          break;
        case 'CCX':
        case 'Toffoli':
          lines.push(`qc.ccx(${g.controls?.[0] ?? 0}, ${g.controls?.[1] ?? 1}, ${g.targets[0]})`);
          break;
        case 'Rx':
          lines.push(`qc.rx(${g.params?.theta ?? Math.PI}, ${g.targets[0]})`);
          break;
        case 'Ry':
          lines.push(`qc.ry(${g.params?.theta ?? Math.PI}, ${g.targets[0]})`);
          break;
        case 'Rz':
          lines.push(`qc.rz(${g.params?.phi ?? g.params?.theta ?? Math.PI}, ${g.targets[0]})`);
          break;
        default:
          lines.push(`# Unrecognized gate: ${g.type}`);
      }
    }

    lines.push('');
    lines.push('qc.measure_all()');
    lines.push('');
    lines.push('# Execute on Aer Simulator');
    lines.push('simulator = AerSimulator()');
    lines.push('result = simulator.run(qc, shots=1024).result()');
    lines.push('counts = result.get_counts()');
    lines.push('print("Measurement Counts:", counts)');

    return lines.join('\n');
  }

  /**
   * Generates PennyLane differentiable quantum code.
   */
  public static toPennyLane(ir: QuantumCircuitIR): string {
    const lines: string[] = [
      '# Generated by Q-Learn Nexus Quantum Transpiler (PennyLane)',
      'import pennylane as qml',
      'import numpy as np',
      '',
      `dev = qml.device("default.qubit", wires=${ir.qubits})`,
      '',
      '@qml.qnode(dev)',
      'def quantum_circuit():',
    ];

    const sorted = [...ir.gates].sort((a, b) => a.stepIndex - b.stepIndex);

    for (const g of sorted) {
      switch (g.type) {
        case 'H':
          lines.push(`    qml.Hadamard(wires=${g.targets[0]})`);
          break;
        case 'X':
          lines.push(`    qml.PauliX(wires=${g.targets[0]})`);
          break;
        case 'Y':
          lines.push(`    qml.PauliY(wires=${g.targets[0]})`);
          break;
        case 'Z':
          lines.push(`    qml.PauliZ(wires=${g.targets[0]})`);
          break;
        case 'S':
          lines.push(`    qml.S(wires=${g.targets[0]})`);
          break;
        case 'T':
          lines.push(`    qml.T(wires=${g.targets[0]})`);
          break;
        case 'CX':
        case 'CNOT':
          lines.push(`    qml.CNOT(wires=[${g.controls?.[0] ?? 0}, ${g.targets[0]}])`);
          break;
        case 'CZ':
          lines.push(`    qml.CZ(wires=[${g.controls?.[0] ?? 0}, ${g.targets[0]}])`);
          break;
        case 'SWAP':
          lines.push(`    qml.SWAP(wires=[${g.targets[0]}, ${g.targets[1] ?? 1}])`);
          break;
        case 'Rx':
          lines.push(`    qml.RX(${g.params?.theta ?? Math.PI}, wires=${g.targets[0]})`);
          break;
        case 'Ry':
          lines.push(`    qml.RY(${g.params?.theta ?? Math.PI}, wires=${g.targets[0]})`);
          break;
        case 'Rz':
          lines.push(`    qml.RZ(${g.params?.phi ?? g.params?.theta ?? Math.PI}, wires=${g.targets[0]})`);
          break;
        default:
          lines.push(`    # Custom Gate: ${g.type}`);
      }
    }

    lines.push('    return qml.probs()');
    lines.push('');
    lines.push('probs = quantum_circuit()');
    lines.push('print("State Probabilities:", probs)');

    return lines.join('\n');
  }

  /**
   * Generates Cirq Python code.
   */
  public static toCirq(ir: QuantumCircuitIR): string {
    const lines: string[] = [
      '# Generated by Q-Learn Nexus Quantum Transpiler (Google Cirq)',
      'import cirq',
      '',
      `qubits = [cirq.LineQubit(i) for i in range(${ir.qubits})]`,
      'circuit = cirq.Circuit()',
      '',
    ];

    const sorted = [...ir.gates].sort((a, b) => a.stepIndex - b.stepIndex);

    for (const g of sorted) {
      switch (g.type) {
        case 'H':
          lines.push(`circuit.append(cirq.H(qubits[${g.targets[0]}]))`);
          break;
        case 'X':
          lines.push(`circuit.append(cirq.X(qubits[${g.targets[0]}]))`);
          break;
        case 'Y':
          lines.push(`circuit.append(cirq.Y(qubits[${g.targets[0]}]))`);
          break;
        case 'Z':
          lines.push(`circuit.append(cirq.Z(qubits[${g.targets[0]}]))`);
          break;
        case 'S':
          lines.push(`circuit.append(cirq.S(qubits[${g.targets[0]}]))`);
          break;
        case 'T':
          lines.push(`circuit.append(cirq.T(qubits[${g.targets[0]}]))`);
          break;
        case 'CX':
        case 'CNOT':
          lines.push(`circuit.append(cirq.CNOT(qubits[${g.controls?.[0] ?? 0}], qubits[${g.targets[0]}]))`);
          break;
        case 'CZ':
          lines.push(`circuit.append(cirq.CZ(qubits[${g.controls?.[0] ?? 0}], qubits[${g.targets[0]}]))`);
          break;
        case 'SWAP':
          lines.push(`circuit.append(cirq.SWAP(qubits[${g.targets[0]}], qubits[${g.targets[1] ?? 1}]))`);
          break;
        default:
          lines.push(`# Custom Gate: ${g.type}`);
      }
    }

    lines.push('');
    lines.push('simulator = cirq.Simulator()');
    lines.push('results = simulator.simulate(circuit)');
    lines.push('print("Final Statevector:\\n", results.state_vector())');

    return lines.join('\n');
  }

  /**
   * Generates OpenQASM 3.0 specification.
   */
  public static toOpenQASM(ir: QuantumCircuitIR): string {
    const lines: string[] = [
      'OPENQASM 3.0;',
      'include "stdgates.inc";',
      '',
      `qubit[${ir.qubits}] q;`,
      `bit[${ir.classicalBits}] c;`,
      '',
    ];

    const sorted = [...ir.gates].sort((a, b) => a.stepIndex - b.stepIndex);

    for (const g of sorted) {
      switch (g.type) {
        case 'H':
          lines.push(`h q[${g.targets[0]}];`);
          break;
        case 'X':
          lines.push(`x q[${g.targets[0]}];`);
          break;
        case 'Y':
          lines.push(`y q[${g.targets[0]}];`);
          break;
        case 'Z':
          lines.push(`z q[${g.targets[0]}];`);
          break;
        case 'S':
          lines.push(`s q[${g.targets[0]}];`);
          break;
        case 'T':
          lines.push(`t q[${g.targets[0]}];`);
          break;
        case 'CX':
        case 'CNOT':
          lines.push(`cx q[${g.controls?.[0] ?? 0}], q[${g.targets[0]}];`);
          break;
        case 'CZ':
          lines.push(`cz q[${g.controls?.[0] ?? 0}], q[${g.targets[0]}];`);
          break;
        case 'SWAP':
          lines.push(`swap q[${g.targets[0]}], q[${g.targets[1] ?? 1}];`);
          break;
        case 'Rx':
          lines.push(`rx(${g.params?.theta ?? Math.PI}) q[${g.targets[0]}];`);
          break;
        case 'Ry':
          lines.push(`ry(${g.params?.theta ?? Math.PI}) q[${g.targets[0]}];`);
          break;
        case 'Rz':
          lines.push(`rz(${g.params?.phi ?? g.params?.theta ?? Math.PI}) q[${g.targets[0]}];`);
          break;
        default:
          lines.push(`// Custom Gate: ${g.type}`);
      }
    }

    lines.push('');
    lines.push('c = measure q;');
    return lines.join('\n');
  }
}
